name: ubuntu

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  tests:
    runs-on: ubuntu-18.04
    env:
      PG: ${{ matrix.postgres-version }}
    strategy:
      fail-fast: false
      matrix:
        postgres-version:
        - '9.3'
        - '9.4'
        - '9.5'
        - '9.6'
        - '10'
        - '11'
        - '12'
        - '13'

    steps:
    - uses: actions/checkout@v1
    - name: Set up packages
      run: |
        set -e
        sudo service postgresql stop
        sudo sed -ri 's/#(create_main_cluster) .*$/\1 = false/' /etc/postgresql-common/createcluster.conf
        if [ $PG = 13 ]; then sudo sed -i -e "s/main/main $PG/" /etc/apt/sources.list.d/pgdg*.list && sudo apt-get -qq update; fi
        if ! sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install postgresql-$PG postgresql-server-dev-$PG; then echo; fi
        sudo pip install --upgrade cpp-coveralls

    - name: Compile and install pg_auth_mon
      run: |
        set -e
        export PATH=/usr/lib/postgresql/$PG/bin:$PATH
        sudo PATH=$PATH make USE_PGXS=1 ENABLE_GCOV=1 install
        sudo PATH=$PATH make USE_PGXS=1 ENABLE_GCOV=1 with_llvm=no clean all install

    - name: Run tests
      run: |
        PATH=/usr/lib/postgresql/$PG/bin:$PATH bash -x test.sh
        if grep -E '(ERROR|FATAL)' test_cluster?/pg_log/postgresql.log | grep -Ev '(no COPY in progress|could not connect to|could not send|the database system is not yet accepting connections|database system is shutting|error reading result of streaming command|database system is starting up|log:noisia)'; then exit 1; fi

    - name: Generate lcov.info
      run: |
        gcov -lr *.[ch]
        lcov --capture --directory . --no-external -o lcov.info

    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: lcov.info
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: ${{ matrix.postgres-version }}
        parallel: true

  finish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true